# Generated by Django 5.2 on 2026-06-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='customuser',
            name='registration_source',
            field=models.CharField(choices=[('local', 'Local Account'), ('google', 'Google Oatuth'), ('facebook', 'Facebook OAuth')], default='local', max_length=20),
        ),
    ]
