# Generated by Django 5.2 on 2026-06-16 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_first_name_customuser_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='registration_source',
        ),
    ]
